apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-go-app-deployment
  labels:
    app: broken-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-go-app
  template:
    metadata:
      labels:
        app: broken-go-app
    spec:
      serviceAccountName: default  # Use the default service account with RBAC permissions
      shareProcessNamespace: true  # This allows the sidecar to see the processes of the main container
      volumes:
        - name: recordings-storage
          emptyDir: {}
        - name: shared-tmp-volume
          emptyDir: {}
      containers:
        # This container is the broken Go application that we want to record
        - name: broken-go-app
          image: undo/broken-go-app:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          ports:
            - containerPort: 8080
              name: broken-go-app
              protocol: TCP
          lifecycle:
            preStop:  # preStop hook to wait for the undo.io/status annotation to be set to 'idle',
                      # to ensure recordings are uploaded before shutdown
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "PreStop hook: Waiting for undo.io/status annotation to be set to 'idle'..."
                    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
                    NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
                    while true; do
                      STATUS=$(curl -s -k -H "Authorization: Bearer $TOKEN" \
                        "https://kubernetes.default.svc/api/v1/namespaces/$NAMESPACE/pods/$HOSTNAME" | \
                        grep -o '"undo.io/status":"[^"]*"' | cut -d'"' -f4 || echo "")
                      if [ "$STATUS" = "idle" ]; then
                        echo "PreStop hook: undo.io/status annotation is now 'idle', allowing container shutdown"
                        break
                      fi
                      echo "PreStop hook: Current status: '$STATUS', waiting for 'idle'..."
                      sleep 2
                    done
          volumeMounts:
            - name: recordings-storage
              mountPath: /recordings
            - name: shared-tmp-volume
              mountPath: /tmp
        # This container is the Undo sidecar that will record the process
        - name: undo-lr-sidecar
          image: undo/undo-lr-sidecar:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
          volumeMounts:
            - name: recordings-storage
              mountPath: /recordings
            - name: shared-tmp-volume
              mountPath: /tmp
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_PROCESS_NAME
              value: "broken-go-app"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: S3_BUCKET_NAME
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: S3_REGION
            - name: S3_KEY_PREFIX
              value: "recordings"
