apiVersion: v1
kind: Service
metadata:
  name: broken-go-app-service
spec:
  type: LoadBalancer 
  selector:
    app: broken-go-app
  ports:
    - name: broken-go-app
      protocol: TCP
      port: 8080
      targetPort: broken-go-app